### ISSUE TITLE
Unit\Length conversion is giving wrong numbers

### ISSUE THREAD

**Issue by slavensaka** [pimlie/php-unit-conversion#10]
foot to meters for the number 136043.25 gives back 124397.9478 instead the correct answer is 41465.9826.

        $convertFromClass = "\PhpUnitConversion\Unit\Length\Foot';
  	$convertToClass = "\PhpUnitConversion\Unit\Length\Meter;
  	$convertFrom = new $convertFromClass($formatNumberToConvert);
  	$convertTo = new $convertToClass();

  	$convertedNum = $convertFrom->to($convertTo);
  	$convertValue = $convertedNum->format($precision, false); // debatable to use (float)
  	$convertNoPrecision = $convertedNum->getValue();
  	$convertSymbol = $convertedNum->getSymbol();
       echo $convertValue; // It's wrong number

**Comment by pimlie** [comment]
Thanks for the report, unfortunately I am unable to reproduce this locally. It gives me 41465 back when I try your code. Not sure how that is possible, maybe there are conflicting name spaces? Do you add your own custom units?

**Comment by slavensaka** [comment]
$foot = new Length\Foot(21);
     echo Length\Meter::from($foot)->format(); 
The Foot class is the issue

     class Foot extends Yard {
        ...
     const FACTOR = 1/3; // This is breaking 
     }

PHP Parse error:  syntax error, unexpected '/', expecting ',' or ';' in /var/www/vhost/biome/vendor/php-unit-conversion/php-unit-conversion/src/Unit/Length/Foot.php on line 10

I tried adding double quotes around it but that messes up the calcs like the above issue i raised first. I forget i tried to that ini the code. 
I'm using PHP 5.5.9-1ubuntu4.29 (cli) (built: Apr 22 2019 18:33:52).

Anyway this can be fixed. Right now it works just fine with the other types of factors. Only the 1/3 forward slash breaks. Need to escape it

**Comment by slavensaka** [comment]
class ImperialNauticalMile extends Yard {
      ...
      const FACTOR = 2026 + 2/3;
     ...
     }
This also breaks. 
PHP Parse error:  syntax error, unexpected '+', expecting ',' or ';' in /var/www/vhost/biome/vendor/php-unit-conversion/php-unit-conversion/src/Unit/Length/ImperialNauticalMile.php on line 10

**Comment by pimlie** [comment]
Strange that you didnt get an error on install because we list in composer.json that we minimally require `"php": ">=5.6.0"`

I am sorry but I wont be supporting php 5.5, its just too old. Please upgrade to a newer version. Is it correct you are running Ubuntu 14.04 btw?! Damn, if so its really time to upgrade, thats the best time you can spent instead of us trying to fix this issue.

**Comment by slavensaka** [comment]
Well yes were in the process of upgrading to latest php, if that's the cause of it not working then I'm ok with upgrading it to 5.6 for a quick fix. You can close this issue.
Are there any more explanation about how adding new custom units maybe?

**Comment by pimlie** [comment]
Except for the readme unfortunately not: https://github.com/pimlie/php-unit-conversion#adding-custom-units

You could have a look though at the tests as we add custom types there too, eg: https://github.com/pimlie/php-unit-conversion/blob/master/tests/UnitTest.php#L57

**Comment by slavensaka** [comment]
Hi im having a hard time figuring out why i get a not found.
I'm trying to add a Headcount.php unit within Amount unit type.
But i get this 
Class 'PhpUnitConversion\Unit\Amount\HeadCount' not found

I'm using the UnitMap::add

     UnitMap::add(
    	dirname(__DIR__, 2) .'/helpers/unitconversion/Fixtures/Amount/HeadCount.php',
    	 "PhpUnitConversion\\Unit",
    	\PhpUnitConversion\Unit\Amount::class
    );

First parameter is the server path that's the correct path to my HeadCount.php
Second im not sure what to use
Third the class of the unit type I want to add it to

This is my HeadCount.php unit

       namespace PhpUnitConversion\Unit\Amount;
       use PhpUnitConversion\Unit\Amount;
       class HeadCount extends Amount
       {
         const FACTOR = 1;
        const SYMBOL = 'hc';
        const LABEL = 'head count';
      }

Initlization:

     $hd = new  \PhpUnitConversion\Unit\Amount\HeadCount(343);

I need to initilize it like above reason i have dynamic way of calling it

      $convertFromClass = "\PhpUnitConversion\Unit\\". $type . "\\" .  $from;
      $convertFrom = new $convertFromClass($formattedNumber);

Looking in Map.php source code the static load()  adds it to self:$paths like this

"[["\/var\/www\/vhost\/biome\/vendor\/php-unit-conversion\/php-unit-conversion\/src\/Unit\/"
"PhpUnitConversion\\Unit"
true
null]

["\/var\/www\/vhost\/biome\/app\/helpers\/unitconversion\/Fixtures\/Amount\/HeadCount.php"
"PhpUnitConversion\\Unit"
true
"PhpUnitConversion\\Unit\\Amount"]]"
