### ISSUE TITLE
Any way to add in a new Unit type for Length

### ISSUE THREAD

**Issue by slavensaka** [pimlie/php-unit-conversion#11]
Would need to add my custom units of measure. Like TonneKilimeter and PassengerKilometer in Length.
How can I do thats outside the scope of the library? 
Something similar to Adding custom units, but only adding units to already defined units.

**Comment by pimlie** [comment]
Hey, have a look at the second example in the section about adding custom units specifies. I think this is what you want to do?

```php
/* If you only want add one unit to an existing unit type, add a third argument with the class name
 * of the unit type you want your unit to add to
 */
UnitMap::add('/path/to/TwoTableSpoons.php', '\\MyUnits', PhpUnitConversion\Unit\Volume::class);
```

**Comment by slavensaka** [comment]
Yes! Exactly. I have no idea how i missed that. 
Ive already added my custom units so I definitely read it sometime ago.
