### ISSUE TITLE
When will be the latest changes available on packagist?

### ISSUE THREAD

**Issue by JoshuaBehrens** [pimlie/php-unit-conversion#6]
I saw it is almost a year ago when the last release has been published. Since then the number of commits doubled. When will be the next release?

**Comment by pimlie** [comment]
As of now :)

Thanks for the reminder!

**Comment by JoshuaBehrens** [comment]
Without a version change? :astonished:

**Comment by pimlie** [comment]
What do you mean? The new version is v1.2.0

**Comment by JoshuaBehrens** [comment]
Ok then the version image was confusing
![image](https://user-images.githubusercontent.com/1133593/50292701-1664d300-0472-11e9-998c-432f06874560.png)

**Comment by pimlie** [comment]
Ah right, yes. Not sure why that badge doesnt update. The direct link also only shows 1.1.0 https://img.shields.io/packagist/v/php-unit-conversion/php-unit-conversion.svg

Will probably be ok tomorrow or something
